// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shurli_grpc/shurlipb/shurli.proto

package shurlipb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WalletInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletInfoRequest) Reset()         { *m = WalletInfoRequest{} }
func (m *WalletInfoRequest) String() string { return proto.CompactTextString(m) }
func (*WalletInfoRequest) ProtoMessage()    {}
func (*WalletInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4d0ef56cd15d2e8, []int{0}
}

func (m *WalletInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletInfoRequest.Unmarshal(m, b)
}
func (m *WalletInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletInfoRequest.Marshal(b, m, deterministic)
}
func (m *WalletInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletInfoRequest.Merge(m, src)
}
func (m *WalletInfoRequest) XXX_Size() int {
	return xxx_messageInfo_WalletInfoRequest.Size(m)
}
func (m *WalletInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WalletInfoRequest proto.InternalMessageInfo

type WalletInfoResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Ticker               string   `protobuf:"bytes,2,opt,name=Ticker,proto3" json:"Ticker,omitempty"`
	Icon                 string   `protobuf:"bytes,3,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Balance              float64  `protobuf:"fixed64,5,opt,name=Balance,proto3" json:"Balance,omitempty"`
	ZBalance             float64  `protobuf:"fixed64,6,opt,name=ZBalance,proto3" json:"ZBalance,omitempty"`
	Blocks               int32    `protobuf:"varint,7,opt,name=Blocks,proto3" json:"Blocks,omitempty"`
	Synced               bool     `protobuf:"varint,8,opt,name=Synced,proto3" json:"Synced,omitempty"`
	Shielded             bool     `protobuf:"varint,9,opt,name=Shielded,proto3" json:"Shielded,omitempty"`
	TValidAddr           bool     `protobuf:"varint,10,opt,name=TValidAddr,proto3" json:"TValidAddr,omitempty"`
	ZValidAddr           bool     `protobuf:"varint,11,opt,name=ZValidAddr,proto3" json:"ZValidAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletInfoResponse) Reset()         { *m = WalletInfoResponse{} }
func (m *WalletInfoResponse) String() string { return proto.CompactTextString(m) }
func (*WalletInfoResponse) ProtoMessage()    {}
func (*WalletInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4d0ef56cd15d2e8, []int{1}
}

func (m *WalletInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletInfoResponse.Unmarshal(m, b)
}
func (m *WalletInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletInfoResponse.Marshal(b, m, deterministic)
}
func (m *WalletInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletInfoResponse.Merge(m, src)
}
func (m *WalletInfoResponse) XXX_Size() int {
	return xxx_messageInfo_WalletInfoResponse.Size(m)
}
func (m *WalletInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WalletInfoResponse proto.InternalMessageInfo

func (m *WalletInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WalletInfoResponse) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *WalletInfoResponse) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *WalletInfoResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *WalletInfoResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *WalletInfoResponse) GetZBalance() float64 {
	if m != nil {
		return m.ZBalance
	}
	return 0
}

func (m *WalletInfoResponse) GetBlocks() int32 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

func (m *WalletInfoResponse) GetSynced() bool {
	if m != nil {
		return m.Synced
	}
	return false
}

func (m *WalletInfoResponse) GetShielded() bool {
	if m != nil {
		return m.Shielded
	}
	return false
}

func (m *WalletInfoResponse) GetTValidAddr() bool {
	if m != nil {
		return m.TValidAddr
	}
	return false
}

func (m *WalletInfoResponse) GetZValidAddr() bool {
	if m != nil {
		return m.ZValidAddr
	}
	return false
}

func init() {
	proto.RegisterType((*WalletInfoRequest)(nil), "shurli.WalletInfoRequest")
	proto.RegisterType((*WalletInfoResponse)(nil), "shurli.WalletInfoResponse")
}

func init() {
	proto.RegisterFile("shurli_grpc/shurlipb/shurli.proto", fileDescriptor_f4d0ef56cd15d2e8)
}

var fileDescriptor_f4d0ef56cd15d2e8 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xcd, 0xdc, 0xba, 0xee, 0x89, 0x07, 0x23, 0x48, 0xdc, 0x41, 0xea, 0x4e, 0x3d, 0x4d,
	0xd0, 0x4f, 0xe0, 0xc0, 0xc3, 0x2e, 0x1e, 0xda, 0x31, 0x61, 0x17, 0xc9, 0x92, 0xa7, 0x2b, 0x8b,
	0x4d, 0x4d, 0x5a, 0xc1, 0x2f, 0xe5, 0x67, 0x94, 0x24, 0xed, 0x3a, 0xd0, 0xdb, 0xfb, 0xbd, 0xdf,
	0x9f, 0x04, 0xfe, 0x0f, 0x6e, 0xed, 0xae, 0x31, 0xaa, 0x78, 0x7d, 0x37, 0x95, 0xb8, 0x0b, 0x73,
	0xb5, 0x6d, 0x87, 0x79, 0x65, 0x74, 0xad, 0x69, 0x14, 0x68, 0x76, 0x09, 0x17, 0x2f, 0x5c, 0x29,
	0xac, 0x97, 0xe5, 0x9b, 0xce, 0xf0, 0xb3, 0x41, 0x5b, 0xcf, 0x7e, 0x06, 0x40, 0x8f, 0xb7, 0xb6,
	0xd2, 0xa5, 0x45, 0x4a, 0x61, 0xf8, 0xcc, 0x3f, 0x90, 0x91, 0x84, 0xa4, 0x93, 0xcc, 0xcf, 0xf4,
	0x0a, 0xa2, 0x55, 0x21, 0xf6, 0x68, 0xd8, 0xc0, 0x6f, 0x5b, 0x72, 0xd9, 0xa5, 0xd0, 0x25, 0x3b,
	0x0d, 0x59, 0x37, 0xbb, 0x6c, 0x5e, 0xf3, 0xba, 0xb1, 0x6c, 0x18, 0xb2, 0x81, 0x28, 0x83, 0xf1,
	0x82, 0x2b, 0x5e, 0x0a, 0x64, 0xa3, 0x84, 0xa4, 0x24, 0xeb, 0x90, 0x4e, 0x21, 0xde, 0x74, 0x2a,
	0xf2, 0xea, 0xc0, 0xee, 0xb5, 0x85, 0xd2, 0x62, 0x6f, 0xd9, 0x38, 0x21, 0xe9, 0x28, 0x6b, 0xc9,
	0xff, 0xf2, 0x5d, 0x0a, 0x94, 0x2c, 0x4e, 0x48, 0x1a, 0x67, 0x2d, 0xb9, 0xb7, 0xf2, 0x5d, 0x81,
	0x4a, 0xa2, 0x64, 0x13, 0x6f, 0x0e, 0x4c, 0x6f, 0x00, 0x56, 0x6b, 0xae, 0x0a, 0xf9, 0x28, 0xa5,
	0x61, 0xe0, 0xed, 0xd1, 0xc6, 0xf9, 0x4d, 0xef, 0xcf, 0x82, 0xef, 0x37, 0xf7, 0x6b, 0x38, 0xcf,
	0x7d, 0x9f, 0x39, 0x9a, 0xaf, 0x42, 0x20, 0x7d, 0x02, 0xe8, 0x0b, 0xa4, 0xd7, 0xf3, 0xb6, 0xfb,
	0x3f, 0x55, 0x4f, 0xa7, 0xff, 0xa9, 0xd0, 0xf7, 0xec, 0x64, 0x01, 0x9b, 0xb8, 0x3b, 0xdf, 0x36,
	0xf2, 0x87, 0x7b, 0xf8, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x63, 0x55, 0xe4, 0x78, 0xdd, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShurliServiceClient is the client API for ShurliService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShurliServiceClient interface {
	//Unary
	WalletInfo(ctx context.Context, in *WalletInfoRequest, opts ...grpc.CallOption) (*WalletInfoResponse, error)
}

type shurliServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShurliServiceClient(cc grpc.ClientConnInterface) ShurliServiceClient {
	return &shurliServiceClient{cc}
}

func (c *shurliServiceClient) WalletInfo(ctx context.Context, in *WalletInfoRequest, opts ...grpc.CallOption) (*WalletInfoResponse, error) {
	out := new(WalletInfoResponse)
	err := c.cc.Invoke(ctx, "/shurli.ShurliService/WalletInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShurliServiceServer is the server API for ShurliService service.
type ShurliServiceServer interface {
	//Unary
	WalletInfo(context.Context, *WalletInfoRequest) (*WalletInfoResponse, error)
}

// UnimplementedShurliServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShurliServiceServer struct {
}

func (*UnimplementedShurliServiceServer) WalletInfo(ctx context.Context, req *WalletInfoRequest) (*WalletInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletInfo not implemented")
}

func RegisterShurliServiceServer(s *grpc.Server, srv ShurliServiceServer) {
	s.RegisterService(&_ShurliService_serviceDesc, srv)
}

func _ShurliService_WalletInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShurliServiceServer).WalletInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shurli.ShurliService/WalletInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShurliServiceServer).WalletInfo(ctx, req.(*WalletInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShurliService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shurli.ShurliService",
	HandlerType: (*ShurliServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WalletInfo",
			Handler:    _ShurliService_WalletInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shurli_grpc/shurlipb/shurli.proto",
}
